# Generated by Django 3.2.15 on 2022-08-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_item',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('placed', 'Placed'), ('packed', 'Packed'), ('transit', 'Transit'), ('delivered', ' Delivered')], default='pla', max_length=9),
        ),
    ]
